### ISSUE TITLE
Test failure for build against simphony-common 0.6.0

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-lammps#124]
```
======================================================================
ERROR: test_0_step_run (simlammps.tests.test_lammps_wrapper.TestLammpsMDEngineFILEIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "simlammps/testing/abc_lammps_md_engine_check.py", line 117, in test_0_step_run
    self.wrapper.run()
  File "simlammps/lammps_wrapper.py", line 328, in run
    self.SD.iter(item_type=CUBA.MATERIAL)])
  File "simlammps/config/script_writer.py", line 86, in get_configuration
    result += ScriptWriter.get_fix(CM)
  File "simlammps/config/script_writer.py", line 130, in get_fix
    _check_configuration(CM)
  File "simlammps/config/script_writer.py", line 185, in _check_configuration
    raise ConfigurationError(msg)
ConfigurationError: Problem with CM component. Missing: CUBA.THERMODYNAMIC_ENSEMBLE
```

Similar errors are present with the same Exception message.
See PR #123 for details

**Comment by ahashibon** [comment]
@mehdisadeghi would you please take a look at this? Thanks.

**Comment by ahashibon** [comment]
Tests need to be updated to use the latest CUDS.

**Comment by mehdisadeghi** [comment]
PRs 132-135 address this issue. Closing.
